### PR TITLE
Add console utilities such as progress bars and add aliases to commands such as "clear".

### PR DESCRIPTION
**Pull request by ghost**
e

### CODE REVIEW

**Comment by robtech21** [comment]
What benefits could you bring to the `dsaklib` module with this? It seems like complete gibberish. Also there are some VSCode dotfiles that you probably forgot to add to `.gitignore`.

**Comment by ghost** [comment]
oh

**Comment by robtech21** [comment]
> oh

Also, please make your commit titles more descriptive. For example, `Added xyz` or `Fixed xyz issue`

**Comment by robtech21** [comment]
@AcaiBerii This is an unreleased module with only the framework and a few test modules. The `clr()` function already has 2 aliases, `cls()` and `clear()`. You can find a list of base commands [here](https://github.com/robtech21/DigitalSwissArmyKnife#base-commands). It'll be a while before anything is released though.

**Pull request closed without merging**
